/// Platform request kinds, logged with each proof-verification failure.
#[derive(Debug, Clone, Copy, Ord, PartialOrd, Eq, PartialEq)]
pub enum RequestType {
    BroadcastStateTransition,
    GetIdentity,
    GetIdentityKeys,
    GetIdentitiesContractKeys,
    GetIdentityNonce,
    GetIdentityContractNonce,
    GetIdentityBalance,
    GetIdentitiesBalances,
    GetIdentityBalanceAndRevision,
    GetEvonodesProposedEpochBlocksByIds,
    GetEvonodesProposedEpochBlocksByRange,
    GetProofs,
    GetDataContract,
    GetDataContractHistory,
    GetDataContracts,
    GetDocuments,
    GetIdentityByPublicKeyHash,
    WaitForStateTransitionResult,
    GetConsensusParams,
    GetProtocolVersionUpgradeState,
    GetProtocolVersionUpgradeVoteStatus,
    GetEpochsInfo,
    GetContestedResources,
    GetContestedResourceVoteState,
    GetContestedResourceVotersForIdentity,
    GetContestedResourceIdentityVotes,
    GetVotePollsByEndDate,
    GetPrefundedSpecializedBalance,
    GetTotalCreditsInPlatform,
    GetPathElements,
    GetStatus,
    GetCurrentQuorumsInfo,
}
