//! Onboarding empty state for the Identities hub.
//!
//! Rendered when the user has zero identities on the active network
//! (`HubLanding::Onboarding`). See design-spec §B.1.

use crate::app::AppAction;
use crate::context::AppContext;
use crate::ui::ScreenType;
use crate::ui::identity::avatar::paint_abstract_avatar;
use crate::ui::theme::{DashColors, ResponseExt};
use eframe::egui::{Align, Layout, RichText, Ui};
use std::sync::Arc;

/// Footprint (glow + glyph) of the abstract avatar shown above the heading.
const AVATAR_DIAMETER: f32 = 140.0;

/// Render the onboarding empty state inside a pre-configured central panel.
///
/// Returns any `AppAction` generated by the user clicking one of the CTAs.
/// Strings are taken verbatim from design-spec §B.1 and are i18n-ready.
pub fn render(ui: &mut Ui, app_context: &Arc<AppContext>) -> AppAction {
    let dark_mode = ui.ctx().global_style().visuals.dark_mode;
    let mut action = AppAction::None;

    // Claim the island's full width so its bordered panel reaches the window
    // edges; the readable column below stays centered and capped at 640px.
    ui.set_min_width(ui.available_width());

    ui.vertical_centered(|ui| {
        // Generous vertical space so the card doesn't hug the top.
        ui.add_space(48.0);
        ui.set_max_width(640.0);

        ui.with_layout(Layout::top_down(Align::Center), |ui| {
            paint_abstract_avatar(ui, AVATAR_DIAMETER);
            ui.add_space(16.0);
            ui.label(
                RichText::new("Welcome to Identities.")
                    .size(28.0)
                    .strong()
                    .color(DashColors::text_primary(dark_mode)),
            );
            ui.add_space(16.0);
            ui.label(
                RichText::new(
                    "An identity is your account on Dash Platform. With one you can pick a \
                     username, send and receive Dash by name, and — if you choose — connect \
                     with people through DashPay.",
                )
                .color(DashColors::text_secondary(dark_mode)),
            );
            ui.add_space(12.0);
            ui.label(
                RichText::new(
                    "You only need a small amount of Dash from your wallet to get started.",
                )
                .color(DashColors::text_secondary(dark_mode)),
            );
            ui.add_space(24.0);

            let primary = egui::Button::new(
                RichText::new("Create my first identity")
                    .strong()
                    .color(egui::Color32::WHITE),
            )
            .fill(DashColors::DASH_BLUE)
            .min_size(egui::vec2(280.0, 40.0));
            let primary_response = ui.add(primary).clickable_tooltip(
                "Start the short setup: pick a username, fund the identity from your wallet, \
                 and confirm.",
            );
            if primary_response.clicked() {
                action =
                    AppAction::AddScreen(ScreenType::AddNewIdentity.create_screen(app_context));
            }

            ui.add_space(8.0);

            let secondary = egui::Button::new(
                RichText::new("I already have an identity — load it")
                    .color(DashColors::text_primary(dark_mode)),
            )
            .fill(DashColors::surface(dark_mode))
            .min_size(egui::vec2(280.0, 36.0));
            let secondary_response = ui.add(secondary).clickable_tooltip(
                "Enter the identity ID and private key to import an existing identity into \
                 this device.",
            );
            if secondary_response.clicked() {
                action = AppAction::AddScreen(
                    ScreenType::AddExistingIdentity.create_screen(app_context),
                );
            }

            if app_context.is_developer_mode() {
                ui.add_space(32.0);
                ui.separator();
                ui.add_space(8.0);
                ui.label(
                    RichText::new("Developer tools:")
                        .color(DashColors::text_secondary(dark_mode))
                        .small(),
                );
                ui.add_space(4.0);
                // Footer ghost links — full wiring in T6 once the devmode routes land.
                ui.label(
                    RichText::new("Create multiple test identities · Load identity by ID")
                        .color(DashColors::text_secondary(dark_mode))
                        .small(),
                );
            }
        });
    });

    action
}
