import { useState } from "react";
import { commands, type GreetResponse } from "./bindings";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ThemeToggle } from "@/components/theme";

function App() {
  const [name, setName] = useState("");
  const [greetResponse, setGreetResponse] = useState<GreetResponse | null>(
    null,
  );
  const [appVersion, setAppVersion] = useState<string | null>(null);
  const [isTauri, setIsTauri] = useState<boolean | null>(null);

  async function handleGreet() {
    try {
      const result = await commands.greet(name);
      setGreetResponse(result);
      setIsTauri(true);
    } catch {
      setGreetResponse({
        message: "Running in browser mode (no Tauri backend).",
        timestamp_ms: Date.now(),
      });
      setIsTauri(false);
    }
  }

  async function handleFetchVersion() {
    try {
      const version = await commands.getAppVersion();
      setAppVersion(version);
    } catch {
      setAppVersion("unknown");
    }
  }

  return (
    <div className="flex min-h-screen flex-col items-center justify-center gap-6 bg-background p-8 text-foreground">
      <div className="absolute right-4 top-4">
        <ThemeToggle />
      </div>
      <div className="flex flex-col items-center gap-2">
        <h1 className="text-4xl font-bold tracking-tight">Dash Evo Tool</h1>
        <p className="text-muted-foreground">Tauri 2.0 + React Frontend</p>
        {isTauri !== null && (
          <Badge variant={isTauri ? "default" : "secondary"}>
            {isTauri ? "Tauri Backend Connected" : "Browser Only"}
          </Badge>
        )}
        {appVersion && (
          <Badge variant="outline">v{appVersion}</Badge>
        )}
      </div>

      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle>IPC Test</CardTitle>
          <CardDescription>
            Test the Tauri IPC bridge by sending a greet command to the Rust
            backend. Uses type-safe bindings generated by tauri-specta.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-4">
          <div className="flex gap-2">
            <Input
              placeholder="Enter your name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") handleGreet();
              }}
            />
            <Button onClick={handleGreet}>Greet</Button>
          </div>
          <Button variant="outline" onClick={handleFetchVersion}>
            Get App Version
          </Button>
          {greetResponse && (
            <p className="rounded-md bg-muted p-3 text-sm">
              {greetResponse.message}
            </p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

export default App;
