/* eslint-disable */
// This file is auto-generated by tauri-specta. Do not edit.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<GreetResponse> {
    return await TAURI_INVOKE("greet", { name });
},
async getAppVersion() : Promise<string> {
    return await TAURI_INVOKE("get_app_version");
},
/**
 * Get the current network state: active network and available networks.
 */
async getNetworkInfo() : Promise<NetworkInfo> {
    return await TAURI_INVOKE("get_network_info");
},
/**
 * Switch the active network. Returns `Ok(())` on success or an error if
 * the requested network has no valid configuration.
 */
async switchNetwork(network: NetworkDto) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_network", { network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the SPV status for all available networks.
 */
async getSpvStatus() : Promise<SpvStatusEvent[]> {
    return await TAURI_INVOKE("get_spv_status");
},
/**
 * Load an existing identity by ID, optionally associating with wallets.
 *
 * Dispatches `IdentityTask::LoadIdentity`. Result arrives via `TaskResultEvent`.
 */
async identityLoad(input: LoadIdentityInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_load", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search for an identity by DPNS name.
 *
 * Dispatches `IdentityTask::SearchIdentityByDpnsName`. Result via event.
 */
async identitySearchByDpnsName(input: SearchIdentityByDpnsNameInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_search_by_dpns_name", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search for an identity from a wallet at a specific index.
 *
 * Dispatches `IdentityTask::SearchIdentityFromWallet`. Result via event.
 */
async identitySearchFromWallet(input: SearchIdentityFromWalletInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_search_from_wallet", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Batch search for identities from a wallet up to a max index.
 *
 * Dispatches `IdentityTask::SearchIdentitiesUpToIndex`. Result via event.
 */
async identitySearchUpToIndex(input: SearchIdentitiesUpToIndexInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_search_up_to_index", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register a DPNS name for an identity.
 *
 * Dispatches `IdentityTask::RegisterDpnsName`. Result via event.
 */
async identityRegisterDpnsName(input: RegisterDpnsNameCommandInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_register_dpns_name", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh a single identity's state from Platform.
 *
 * Dispatches `IdentityTask::RefreshIdentity`. Result via event.
 */
async identityRefresh(input: RefreshIdentityInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_refresh", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh all loaded identities' DPNS names.
 *
 * Dispatches `IdentityTask::RefreshLoadedIdentitiesOwnedDPNSNames`. Result via event.
 */
async identityRefreshDpnsNames() : Promise<DispatchTaskResponse> {
    return await TAURI_INVOKE("identity_refresh_dpns_names");
},
/**
 * Withdraw credits from an identity to a Core address.
 *
 * Dispatches `IdentityTask::WithdrawFromIdentity`. Result via event.
 */
async identityWithdraw(input: WithdrawFromIdentityInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_withdraw", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Transfer credits from one identity to another.
 *
 * Dispatches `IdentityTask::Transfer`. Result via event.
 */
async identityTransfer(input: TransferCreditsInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_transfer", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a key to an identity.
 *
 * Dispatches `IdentityTask::AddKeyToIdentity`. Result via event.
 */
async identityAddKey(input: AddKeyToIdentityInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_add_key", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Disable one or more keys on an identity.
 *
 * Dispatches `IdentityTask::DisableKeys`. Result via event.
 */
async identityDisableKeys(input: DisableKeysInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_disable_keys", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replace a key on an identity (disable old + add new atomically).
 *
 * Dispatches `IdentityTask::ReplaceKey`. Result via event.
 */
async identityReplaceKey(input: ReplaceKeyInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_replace_key", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load all local qualified identities from the database.
 */
async identityListLocal() : Promise<Result<QualifiedIdentityDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_list_local") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load all local user identities (non-masternode/evonode).
 */
async identityListUser() : Promise<Result<QualifiedIdentityDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_list_user") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load all local voting identities.
 */
async identityListVoting() : Promise<Result<QualifiedIdentityDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_list_voting") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single identity by its ID.
 */
async identityGetById(identityId: string) : Promise<Result<QualifiedIdentityDto | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_get_by_id", { identityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the alias for an identity.
 */
async identitySetAlias(input: SetIdentityAliasInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_set_alias", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the alias for an identity.
 */
async identityGetAlias(identityId: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_get_alias", { identityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load the custom identity ordering.
 */
async identityLoadOrder() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_load_order") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save the custom identity ordering.
 */
async identitySaveOrder(input: SaveIdentityOrderInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_save_order", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a local identity from the database.
 */
async identityDelete(input: DeleteIdentityInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_delete", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get identity summaries suitable for dropdown selectors.
 */
async identityListSummaries() : Promise<Result<IdentitySummaryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_list_summaries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all local DPNS names across all loaded identities.
 */
async identityLocalDpnsNames() : Promise<Result<DpnsNameEntryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_local_dpns_names") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the best chain lock for the active network.
 *
 * Dispatches `CoreTask::GetBestChainLock`. Result via `TaskResultEvent`.
 */
async coreGetBestChainLock() : Promise<DispatchTaskResponse> {
    return await TAURI_INVOKE("core_get_best_chain_lock");
},
/**
 * Get the best chain locks for all configured networks.
 *
 * Dispatches `CoreTask::GetBestChainLocks`. Result via `TaskResultEvent`.
 */
async coreGetBestChainLocks() : Promise<DispatchTaskResponse> {
    return await TAURI_INVOKE("core_get_best_chain_locks");
},
/**
 * Refresh an HD wallet's info from Core, optionally syncing Platform balances.
 *
 * Dispatches `CoreTask::RefreshWalletInfo`. Result via `TaskResultEvent`.
 */
async coreRefreshWalletInfo(input: RefreshWalletInfoInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_refresh_wallet_info", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh a single-key wallet's info from Core.
 *
 * Dispatches `CoreTask::RefreshSingleKeyWalletInfo`. Result via `TaskResultEvent`.
 */
async coreRefreshSingleKeyWalletInfo(input: RefreshSingleKeyWalletInfoInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_refresh_single_key_wallet_info", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start DashQT on the active network.
 *
 * Dispatches `CoreTask::StartDashQT`. Result via `TaskResultEvent`.
 */
async coreStartDashQt(input: StartDashQtInput) : Promise<DispatchTaskResponse> {
    return await TAURI_INVOKE("core_start_dash_qt", { input });
},
/**
 * Create an asset lock for identity registration.
 *
 * Dispatches `CoreTask::CreateRegistrationAssetLock`. Result via `TaskResultEvent`.
 */
async coreCreateRegistrationAssetLock(input: CreateRegistrationAssetLockInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_create_registration_asset_lock", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create an asset lock for identity top-up.
 *
 * Dispatches `CoreTask::CreateTopUpAssetLock`. Result via `TaskResultEvent`.
 */
async coreCreateTopUpAssetLock(input: CreateTopUpAssetLockInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_create_top_up_asset_lock", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a payment from an HD wallet.
 *
 * Dispatches `CoreTask::SendWalletPayment`. Result via `TaskResultEvent`.
 */
async coreSendWalletPayment(input: SendWalletPaymentInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_send_wallet_payment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a payment from a single-key wallet.
 *
 * Dispatches `CoreTask::SendSingleKeyWalletPayment`. Result via `TaskResultEvent`.
 */
async coreSendSingleKeyWalletPayment(input: SendSingleKeyWalletPaymentInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_send_single_key_wallet_payment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recover asset locks from an HD wallet.
 *
 * Dispatches `CoreTask::RecoverAssetLocks`. Result via `TaskResultEvent`.
 */
async coreRecoverAssetLocks(input: RecoverAssetLocksInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_recover_asset_locks", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate a new receive address for an HD wallet.
 *
 * Dispatches `WalletTask::GenerateReceiveAddress`. Result via `TaskResultEvent`.
 */
async walletGenerateReceiveAddress(input: GenerateReceiveAddressInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_generate_receive_address", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch platform address balances for a wallet.
 *
 * Dispatches `WalletTask::FetchPlatformAddressBalances`. Result via `TaskResultEvent`.
 */
async walletFetchPlatformAddressBalances(input: FetchPlatformAddressBalancesInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_fetch_platform_address_balances", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Transfer credits between platform addresses.
 *
 * Dispatches `WalletTask::TransferPlatformCredits`. Result via `TaskResultEvent`.
 */
async walletTransferPlatformCredits(input: TransferPlatformCreditsInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_transfer_platform_credits", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Withdraw from platform addresses to a Core script.
 *
 * Dispatches `WalletTask::WithdrawFromPlatformAddress`. Result via `TaskResultEvent`.
 */
async walletWithdrawFromPlatformAddress(input: WithdrawFromPlatformAddressInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_withdraw_from_platform_address", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fund a platform address from wallet UTXOs.
 *
 * Dispatches `WalletTask::FundPlatformAddressFromWalletUtxos`. Result via `TaskResultEvent`.
 */
async walletFundPlatformAddressFromUtxos(input: FundPlatformAddressFromWalletUtxosInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_fund_platform_address_from_utxos", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all loaded wallets (HD + single-key) with current state.
 */
async walletListAll() : Promise<Result<WalletListDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_list_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single HD wallet by seed hash.
 */
async walletGetHd(walletSeedHash: string) : Promise<Result<WalletDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_get_hd", { walletSeedHash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single-key wallet by key hash.
 */
async walletGetSingleKey(keyHash: string) : Promise<Result<SingleKeyWalletDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_get_single_key", { keyHash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Select a wallet (HD or single-key) as the active wallet.
 */
async walletSelect(input: SelectWalletInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_select", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the alias for an HD wallet.
 */
async walletSetAlias(input: SetWalletAliasInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_set_alias", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the alias for a single-key wallet.
 */
async walletSetSingleKeyAlias(input: SetSingleKeyWalletAliasInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_set_single_key_alias", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove an HD wallet from the application.
 */
async walletRemove(input: RemoveWalletInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_remove", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a single-key wallet from the application.
 */
async walletRemoveSingleKey(input: RemoveSingleKeyWalletInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_remove_single_key", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start SPV for the current network.
 */
async walletStartSpv() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_start_spv") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop SPV for the current network.
 */
async walletStopSpv() : Promise<void> {
    await TAURI_INVOKE("wallet_stop_spv");
},
/**
 * Clear SPV data for the current network.
 */
async walletClearSpvData() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_clear_spv_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Notify the backend that a wallet has been unlocked (triggers SPV wallet load).
 */
async walletNotifyUnlocked(walletSeedHash: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_notify_unlocked", { walletSeedHash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Notify the backend that a wallet has been locked (triggers SPV wallet unload).
 */
async walletNotifyLocked(walletSeedHash: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_notify_locked", { walletSeedHash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
scheduledVoteExecutedEvent: ScheduledVoteExecutedEvent,
spvStatusEvent: SpvStatusEvent,
taskErrorEvent: TaskErrorEvent,
taskResultEvent: TaskResultEvent,
walletUpdatedEvent: WalletUpdatedEvent,
zmqChainLockedBlockEvent: ZmqChainLockedBlockEvent,
zmqConnectionStatusEvent: ZmqConnectionStatusEvent,
zmqIsLockedTransactionEvent: ZmqIsLockedTransactionEvent
}>({
scheduledVoteExecutedEvent: "scheduled-vote-executed-event",
spvStatusEvent: "spv-status-event",
taskErrorEvent: "task-error-event",
taskResultEvent: "task-result-event",
walletUpdatedEvent: "wallet-updated-event",
zmqChainLockedBlockEvent: "zmq-chain-locked-block-event",
zmqConnectionStatusEvent: "zmq-connection-status-event",
zmqIsLockedTransactionEvent: "zmq-is-locked-transaction-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Input for adding a key to an identity.
 */
export type AddKeyToIdentityInput = {
/**
 * Identity ID (hex).
 */
identityId: string;
/**
 * Key type (e.g., "ECDSA_SECP256K1", "BLS12_381").
 */
keyType: string;
/**
 * Key purpose (e.g., "AUTHENTICATION", "VOTING", "TRANSFER").
 */
purpose: string;
/**
 * Security level (e.g., "HIGH", "MEDIUM").
 */
securityLevel: string;
/**
 * Private key as hex string (32 bytes).
 */
privateKeyHex: string }
/**
 * An unused asset lock available for identity operations.
 */
export type AssetLockDto = {
/**
 * Transaction ID as hex string.
 */
txid: string;
/**
 * Address holding the locked funds.
 */
address: string;
/**
 * Amount locked in credits.
 */
amount: number;
/**
 * Whether an instant lock has been received.
 */
hasInstantLock: boolean;
/**
 * Whether an asset lock proof has been generated.
 */
hasAssetLockProof: boolean }
/**
 * Input for creating a registration asset lock.
 */
export type CreateRegistrationAssetLockInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string;
/**
 * Amount in credits to lock.
 */
amountCredits: number;
/**
 * Identity index for the registration.
 */
identityIndex: number }
/**
 * Input for creating a top-up asset lock.
 */
export type CreateTopUpAssetLockInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string;
/**
 * Amount in credits to lock.
 */
amountCredits: number;
/**
 * Identity index.
 */
identityIndex: number;
/**
 * Top-up index within the identity.
 */
topUpIndex: number }
/**
 * Input for deleting a local identity.
 */
export type DeleteIdentityInput = {
/**
 * Identity ID (hex) to delete.
 */
identityId: string }
/**
 * Input for disabling keys on an identity.
 */
export type DisableKeysInput = {
/**
 * Identity ID (hex).
 */
identityId: string;
/**
 * Key IDs to disable.
 */
keyIds: number[] }
/**
 * Response from dispatching a backend task.
 */
export type DispatchTaskResponse = {
/**
 * Unique task ID. Listen for `TaskResultEvent` or `TaskErrorEvent` with
 * this ID to receive the result.
 */
taskId: string }
/**
 * A DPNS name entry with its owning identity.
 */
export type DpnsNameEntryDto = {
/**
 * Identity ID (hex) that owns this name.
 */
identityId: string;
/**
 * The DPNS name (e.g., "alice.dash").
 */
name: string;
/**
 * Timestamp when the name was acquired.
 */
acquiredAt: number }
/**
 * DPNS name info attached to an identity.
 */
export type DpnsNameInfoDto = {
/**
 * The registered DPNS name (e.g., "alice.dash").
 */
name: string;
/**
 * Timestamp when the name was acquired.
 */
acquiredAt: number }
/**
 * Input for fetching platform address balances.
 */
export type FetchPlatformAddressBalancesInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string;
/**
 * Sync mode to use.
 */
syncMode: PlatformSyncModeDto }
/**
 * Input for funding a platform address from wallet UTXOs.
 */
export type FundPlatformAddressFromWalletUtxosInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string;
/**
 * Amount in duffs to lock.
 */
amount: number;
/**
 * Destination platform address.
 */
destination: string;
/**
 * Whether fees are deducted from the output amount.
 */
feeDeductFromOutput: boolean }
/**
 * Input for generating a receive address.
 */
export type GenerateReceiveAddressInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string }
/**
 * A sample DTO demonstrating tauri-specta type generation.
 */
export type GreetResponse = { message: string; timestamp_ms: number }
/**
 * A public key on an identity.
 */
export type IdentityKeyDto = {
/**
 * Key ID within the identity.
 */
keyId: number;
/**
 * Key type (ECDSA_SECP256K1, BLS12_381, ECDSA_HASH160, etc.).
 */
keyType: string;
/**
 * Key purpose (AUTHENTICATION, VOTING, TRANSFER, OWNER, etc.).
 */
purpose: string;
/**
 * Security level (MASTER, CRITICAL, HIGH, MEDIUM, etc.).
 */
securityLevel: string;
/**
 * Public key data as hex string.
 */
data: string;
/**
 * Whether this key is disabled.
 */
isDisabled: boolean;
/**
 * Disabled at timestamp (if disabled).
 */
disabledAt: number | null;
/**
 * Whether we have the corresponding private key in local storage.
 */
hasPrivateKey: boolean }
/**
 * Status of an identity on the platform.
 */
export type IdentityStatusDto = "unknown" | "pendingCreation" | "active" | "notFound" | "failedCreation"
/**
 * Minimal identity reference for dropdowns and selectors.
 */
export type IdentitySummaryDto = {
/**
 * Platform identifier as hex string.
 */
id: string;
/**
 * Display name: alias or truncated ID.
 */
displayName: string;
/**
 * Identity type.
 */
identityType: IdentityTypeDto;
/**
 * Current balance in credits.
 */
balance: number }
/**
 * Type of identity (User, Masternode, Evonode).
 */
export type IdentityTypeDto = "user" | "masternode" | "evonode"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Input for loading an existing identity by ID or from a wallet.
 */
export type LoadIdentityInput = {
/**
 * Identity ID as hex or base58 string.
 */
identityId: string;
/**
 * Type of identity (User, Masternode, Evonode).
 */
identityType: IdentityTypeDto;
/**
 * User alias to assign.
 */
alias: string;
/**
 * Voting private key (hex or WIF, empty string if none).
 */
votingPrivateKey: string;
/**
 * Owner private key (hex or WIF, empty string if none).
 */
ownerPrivateKey: string;
/**
 * Payout address private key (hex or WIF, empty string if none).
 */
payoutAddressPrivateKey: string;
/**
 * Additional private keys (hex or WIF).
 */
keys: string[];
/**
 * Whether to try deriving keys from loaded wallets.
 */
deriveKeysFromWallets: boolean;
/**
 * Optional wallet seed hash to associate with.
 */
selectedWalletSeedHash: string | null }
/**
 * Network identifier matching Dash SDK's Network enum.
 */
export type NetworkDto = "dash" | "testnet" | "devnet" | "regtest"
/**
 * Network availability info returned to the frontend.
 */
export type NetworkInfo = {
/**
 * Currently active network.
 */
activeNetwork: NetworkDto;
/**
 * All networks that have valid configurations.
 */
availableNetworks: NetworkDto[] }
/**
 * A payment recipient.
 */
export type PaymentRecipientDto = { address: string; amount: number }
/**
 * A platform address amount pair for transfer inputs/outputs.
 */
export type PlatformAddressAmountDto = {
/**
 * The address string.
 */
address: string;
/**
 * Amount in credits.
 */
amount: number }
/**
 * Platform address info (DIP-17).
 */
export type PlatformAddressDto = {
/**
 * The Core address string.
 */
address: string;
/**
 * Balance in credits.
 */
balance: number;
/**
 * Current nonce.
 */
nonce: number }
/**
 * Platform sync mode DTO for the IPC boundary.
 */
export type PlatformSyncModeDto = "auto" | "forceFull" | "terminalOnly"
/**
 * Serializable version of `QualifiedIdentity`.
 * This is the primary identity DTO sent to the frontend for display and selection.
 */
export type QualifiedIdentityDto = {
/**
 * Platform identifier as hex string.
 */
id: string;
/**
 * Identity type (User, Masternode, Evonode).
 */
identityType: IdentityTypeDto;
/**
 * User-assigned alias.
 */
alias: string | null;
/**
 * Current balance in credits.
 */
balance: number;
/**
 * Public keys on this identity.
 */
keys: IdentityKeyDto[];
/**
 * DPNS names registered for this identity.
 */
dpnsNames: DpnsNameInfoDto[];
/**
 * Seed hashes of associated wallets (hex-encoded).
 */
associatedWalletHashes: string[];
/**
 * The wallet index used during registration (if applicable).
 */
walletIndex: number | null;
/**
 * Top-up history: map of index → amount.
 */
topUps: TopUpEntryDto[];
/**
 * Current status on the platform.
 */
status: IdentityStatusDto;
/**
 * Network this identity belongs to.
 */
network: NetworkDto;
/**
 * Associated voter identity ID (if any, for masternodes/evonodes).
 */
voterIdentityId: string | null;
/**
 * Associated operator identity ID (if any).
 */
operatorIdentityId: string | null }
/**
 * Input for recovering asset locks from a wallet.
 */
export type RecoverAssetLocksInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string }
/**
 * Input for refreshing a single identity.
 */
export type RefreshIdentityInput = {
/**
 * Identity ID (hex) to refresh.
 */
identityId: string }
/**
 * Input for refreshing a single-key wallet from Core.
 */
export type RefreshSingleKeyWalletInfoInput = {
/**
 * Single-key wallet hash (hex).
 */
keyHash: string }
/**
 * Input for refreshing an HD wallet from Core.
 */
export type RefreshWalletInfoInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string;
/**
 * Optional platform sync mode. None = skip platform sync.
 */
platformSyncMode: PlatformSyncModeDto | null }
/**
 * Input for registering a DPNS name.
 */
export type RegisterDpnsNameCommandInput = {
/**
 * Identity ID (hex) that will own the name.
 */
identityId: string;
/**
 * The DPNS name to register (without .dash suffix).
 */
name: string }
/**
 * Input for removing a single-key wallet.
 */
export type RemoveSingleKeyWalletInput = {
/**
 * Key hash (hex).
 */
keyHash: string }
/**
 * Input for removing a wallet.
 */
export type RemoveWalletInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string }
/**
 * Input for replacing a key on an identity.
 */
export type ReplaceKeyInput = {
/**
 * Identity ID (hex).
 */
identityId: string;
/**
 * Key ID to replace (old key).
 */
oldKeyId: number;
/**
 * New key type.
 */
newKeyType: string;
/**
 * New key purpose.
 */
newPurpose: string;
/**
 * New security level.
 */
newSecurityLevel: string;
/**
 * New private key as hex string (32 bytes).
 */
newPrivateKeyHex: string }
/**
 * Input for saving custom identity ordering.
 */
export type SaveIdentityOrderInput = {
/**
 * Ordered list of identity IDs (hex).
 */
identityIds: string[] }
/**
 * Emitted when a scheduled vote is automatically cast.
 */
export type ScheduledVoteExecutedEvent = {
/**
 * The contested name the vote was for.
 */
contestedName: string;
/**
 * Voter identity ID (hex).
 */
voterId: string;
/**
 * Whether the vote was cast successfully.
 */
success: boolean;
/**
 * Error message if the vote failed.
 */
error: string | null }
/**
 * Input for batch search of identities from a wallet.
 */
export type SearchIdentitiesUpToIndexInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string;
/**
 * Maximum identity index to search up to.
 */
maxIdentityIndex: number }
/**
 * Input for searching identity by DPNS name.
 */
export type SearchIdentityByDpnsNameInput = {
/**
 * DPNS name without .dash suffix.
 */
name: string;
/**
 * Optional wallet seed hash for key derivation.
 */
walletSeedHash: string | null }
/**
 * Input for searching identities from a wallet.
 */
export type SearchIdentityFromWalletInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string;
/**
 * Identity index to search at.
 */
identityIndex: number }
/**
 * Input for selecting a wallet.
 */
export type SelectWalletInput = {
/**
 * Which wallet to select: HD (by seed hash), SingleKey (by key hash), or None (deselect).
 */
selected: WalletRefDto | null }
/**
 * Input for sending a payment from a single-key wallet.
 */
export type SendSingleKeyWalletPaymentInput = {
/**
 * Single-key wallet hash (hex).
 */
keyHash: string;
/**
 * Payment recipients.
 */
recipients: PaymentRecipientDto[];
/**
 * Whether to subtract the fee from the send amount.
 */
subtractFeeFromAmount: boolean;
/**
 * Optional memo.
 */
memo: string | null;
/**
 * Optional override fee in duffs.
 */
overrideFee: number | null }
/**
 * Input for sending a wallet payment (HD wallet).
 */
export type SendWalletPaymentInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string;
/**
 * Payment recipients.
 */
recipients: PaymentRecipientDto[];
/**
 * Whether to subtract the fee from the send amount.
 */
subtractFeeFromAmount: boolean;
/**
 * Optional memo.
 */
memo: string | null;
/**
 * Optional override fee in duffs (for retry after min relay fee error).
 */
overrideFee: number | null }
/**
 * Input for setting identity alias.
 */
export type SetIdentityAliasInput = {
/**
 * Identity ID (hex).
 */
identityId: string;
/**
 * New alias (None to clear).
 */
alias: string | null }
/**
 * Input for setting a single-key wallet alias.
 */
export type SetSingleKeyWalletAliasInput = {
/**
 * Key hash (hex).
 */
keyHash: string;
/**
 * New alias (None to clear).
 */
alias: string | null }
/**
 * Input for setting a wallet alias.
 */
export type SetWalletAliasInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string;
/**
 * New alias (None to clear).
 */
alias: string | null }
/**
 * Serializable summary of a single-key wallet.
 * Replaces `SingleKeyWallet` for IPC. Does NOT include private key material.
 */
export type SingleKeyWalletDto = {
/**
 * SHA-256 hex hash of the private key (unique identifier).
 */
keyHash: string;
/**
 * Whether this wallet requires a password to unlock.
 */
usesPassword: boolean;
/**
 * The public key as hex string.
 */
publicKey: string;
/**
 * The P2PKH address string.
 */
address: string;
/**
 * User-assigned alias.
 */
alias: string | null;
/**
 * Confirmed balance in duffs.
 */
confirmedBalance: number;
/**
 * Unconfirmed balance in duffs.
 */
unconfirmedBalance: number;
/**
 * Total balance in duffs.
 */
totalBalance: number;
/**
 * Number of UTXOs.
 */
utxoCount: number }
/**
 * High-level SPV status values.
 */
export type SpvStatusDto = "idle" | "starting" | "syncing" | "running" | "stopping" | "stopped" | "error"
/**
 * Emitted when SPV sync status changes.
 */
export type SpvStatusEvent = {
/**
 * The network this SPV instance belongs to.
 */
network: NetworkDto;
/**
 * Current SPV status.
 */
status: SpvStatusDto;
/**
 * Sync progress as a percentage (0.0–100.0), if syncing.
 */
syncProgressPct: number | null;
/**
 * Current header height, if known.
 */
headerHeight: number | null;
/**
 * Number of connected peers.
 */
connectedPeers: number;
/**
 * Error message, if status is Error.
 */
error: string | null }
/**
 * Input for starting DashQT.
 */
export type StartDashQtInput = {
/**
 * Path to the custom Dash-Qt binary.
 */
dashQtPath: string;
/**
 * Whether to overwrite dash.conf.
 */
overwriteDashConf: boolean }
/**
 * Emitted when a backend task fails.
 */
export type TaskErrorEvent = {
/**
 * Unique task ID assigned at dispatch time.
 */
taskId: string;
/**
 * User-friendly error message suitable for display.
 */
message: string;
/**
 * Technical error details for debugging.
 */
details: string;
/**
 * Whether the operation can be retried.
 */
recoverable: boolean }
/**
 * Emitted when a backend task completes successfully.
 *
 * The `result_type` field is a discriminant string (e.g. "Identity", "Wallet",
 * "Contract") that the frontend can match on. The `payload` is the serialized
 * result data as JSON value. This design avoids needing to represent the entire
 * `BackendTaskSuccessResult` enum in the TypeScript type system up front —
 * individual domain result types will be defined as the IPC commands are
 * implemented in phases 1.4–1.7.
 */
export type TaskResultEvent = {
/**
 * Unique task ID assigned at dispatch time.
 */
taskId: string;
/**
 * The domain of the result (e.g. "Identity", "Wallet", "None", "Refresh").
 */
resultType: string;
/**
 * The serialized result payload. `null` for `None` and `Refresh` results.
 */
payload: JsonValue | null }
/**
 * A top-up history entry.
 */
export type TopUpEntryDto = { index: number; amount: number }
/**
 * Input for transferring credits to another identity.
 */
export type TransferCreditsInput = {
/**
 * Source identity ID (hex).
 */
fromIdentityId: string;
/**
 * Destination identity ID (hex).
 */
toIdentityId: string;
/**
 * Amount to transfer in credits.
 */
credits: number;
/**
 * Optional key ID to use for signing.
 */
keyId: number | null }
/**
 * Input for transferring credits between platform addresses.
 */
export type TransferPlatformCreditsInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string;
/**
 * Source addresses with amounts to transfer.
 */
inputs: PlatformAddressAmountDto[];
/**
 * Destination addresses with amounts.
 */
outputs: PlatformAddressAmountDto[];
/**
 * Index of the input to deduct fees from (in sorted order).
 */
feePayerIndex: number }
/**
 * An address within an HD wallet.
 */
export type WalletAddressDto = {
/**
 * The address string (e.g., "XpYv3N...").
 */
address: string;
/**
 * Current balance in duffs.
 */
balance: number;
/**
 * Total received over lifetime in duffs.
 */
totalReceived: number;
/**
 * Derivation path as string (e.g., "m/44'/5'/0'/0/0").
 */
derivationPath: string }
/**
 * Serializable summary of an HD wallet, suitable for list views.
 * Replaces `Wallet` for IPC. Does NOT include private key material.
 */
export type WalletDto = {
/**
 * SHA-256 hex hash of the wallet seed (unique identifier).
 */
seedHash: string;
/**
 * Whether this wallet requires a password to unlock.
 */
usesPassword: boolean;
/**
 * User-assigned alias (e.g., "My Main Wallet").
 */
alias: string | null;
/**
 * Whether this is the main wallet.
 */
isMain: boolean;
/**
 * Confirmed balance in duffs.
 */
confirmedBalance: number;
/**
 * Unconfirmed balance in duffs.
 */
unconfirmedBalance: number;
/**
 * Total balance in duffs (confirmed + unconfirmed).
 */
totalBalance: number;
/**
 * Known addresses with their string representation and balance.
 */
addresses: WalletAddressDto[];
/**
 * Transactions associated with this wallet.
 */
transactions: WalletTransactionDto[];
/**
 * Unused asset locks available for identity creation/top-up.
 */
unusedAssetLocks: AssetLockDto[];
/**
 * Platform address info (DIP-17).
 */
platformAddresses: PlatformAddressDto[];
/**
 * Identity indexes registered from this wallet.
 */
identityIndexes: number[];
/**
 * Password hint (if set).
 */
passwordHint: string | null }
/**
 * Summary of all wallets for the wallet list screen.
 */
export type WalletListDto = { hdWallets: WalletDto[]; singleKeyWallets: SingleKeyWalletDto[];
/**
 * Which wallet is currently selected (if any).
 */
selected: WalletRefDto | null }
/**
 * Unified wallet reference — either HD or single-key.
 */
export type WalletRefDto =
/**
 * HD wallet, referenced by seed hash.
 */
{ type: "hd"; seedHash: string } |
/**
 * Single-key wallet, referenced by key hash.
 */
{ type: "singleKey"; keyHash: string }
/**
 * A wallet transaction.
 */
export type WalletTransactionDto = {
/**
 * Transaction ID as hex string.
 */
txid: string;
/**
 * Unix timestamp.
 */
timestamp: number;
/**
 * Block height (None if unconfirmed).
 */
height: number | null;
/**
 * Block hash as hex string (None if unconfirmed).
 */
blockHash: string | null;
/**
 * Net amount change in duffs (positive = incoming, negative = outgoing).
 */
netAmount: number;
/**
 * Transaction fee in duffs (if known).
 */
fee: number | null;
/**
 * User-assigned label.
 */
label: string | null;
/**
 * Whether all inputs are ours.
 */
isOurs: boolean }
/**
 * Emitted when a wallet's balance or state changes.
 */
export type WalletUpdatedEvent = {
/**
 * Which wallet changed (seed hash, hex-encoded).
 */
walletSeedHash: string;
/**
 * The network this wallet belongs to.
 */
network: NetworkDto }
/**
 * Input for withdrawing credits from an identity.
 */
export type WithdrawFromIdentityInput = {
/**
 * Identity ID (hex) to withdraw from.
 */
identityId: string;
/**
 * Optional destination Core address.
 */
toAddress: string | null;
/**
 * Amount to withdraw in credits.
 */
credits: number;
/**
 * Optional key ID to use for signing.
 */
keyId: number | null }
/**
 * Input for withdrawing from a platform address to Core.
 */
export type WithdrawFromPlatformAddressInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string;
/**
 * Platform addresses and amounts to withdraw.
 */
inputs: PlatformAddressAmountDto[];
/**
 * Core script (hex) to receive the withdrawal.
 */
outputScriptHex: string;
/**
 * Core fee per byte.
 */
coreFeePerByte: number;
/**
 * Index of the input to deduct fees from.
 */
feePayerIndex: number }
/**
 * Emitted when a chain-locked block is received via ZMQ.
 */
export type ZmqChainLockedBlockEvent = {
/**
 * The network this event belongs to.
 */
network: NetworkDto;
/**
 * Block height.
 */
blockHeight: number;
/**
 * Block hash (hex).
 */
blockHash: string;
/**
 * Number of transactions in the block.
 */
txCount: number }
/**
 * Emitted when ZMQ connection status changes.
 */
export type ZmqConnectionStatusEvent = {
/**
 * The network this status change belongs to.
 */
network: NetworkDto;
/**
 * Whether ZMQ is currently connected.
 */
connected: boolean }
/**
 * Emitted when an InstantSend-locked transaction is received via ZMQ.
 */
export type ZmqIsLockedTransactionEvent = {
/**
 * The network this event belongs to.
 */
network: NetworkDto;
/**
 * Transaction ID (hex).
 */
txid: string;
/**
 * Serialized transaction data (hex).
 */
rawTx: string;
/**
 * Number of UTXOs affected by this transaction.
 */
affectedUtxoCount: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
