/* eslint-disable */
// This file is auto-generated by tauri-specta. Do not edit.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<GreetResponse> {
    return await TAURI_INVOKE("greet", { name });
},
async getAppVersion() : Promise<string> {
    return await TAURI_INVOKE("get_app_version");
},
/**
 * Get the current network state: active network and available networks.
 */
async getNetworkInfo() : Promise<NetworkInfo> {
    return await TAURI_INVOKE("get_network_info");
},
/**
 * Switch the active network. Returns `Ok(())` on success or an error if
 * the requested network has no valid configuration.
 */
async switchNetwork(network: NetworkDto) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_network", { network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the SPV status for all available networks.
 */
async getSpvStatus() : Promise<SpvStatusEvent[]> {
    return await TAURI_INVOKE("get_spv_status");
},
/**
 * Load an existing identity by ID, optionally associating with wallets.
 *
 * Dispatches `IdentityTask::LoadIdentity`. Result arrives via `TaskResultEvent`.
 */
async identityLoad(input: LoadIdentityInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_load", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search for an identity by DPNS name.
 *
 * Dispatches `IdentityTask::SearchIdentityByDpnsName`. Result via event.
 */
async identitySearchByDpnsName(input: SearchIdentityByDpnsNameInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_search_by_dpns_name", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search for an identity from a wallet at a specific index.
 *
 * Dispatches `IdentityTask::SearchIdentityFromWallet`. Result via event.
 */
async identitySearchFromWallet(input: SearchIdentityFromWalletInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_search_from_wallet", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Batch search for identities from a wallet up to a max index.
 *
 * Dispatches `IdentityTask::SearchIdentitiesUpToIndex`. Result via event.
 */
async identitySearchUpToIndex(input: SearchIdentitiesUpToIndexInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_search_up_to_index", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register a DPNS name for an identity.
 *
 * Dispatches `IdentityTask::RegisterDpnsName`. Result via event.
 */
async identityRegisterDpnsName(input: RegisterDpnsNameCommandInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_register_dpns_name", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh a single identity's state from Platform.
 *
 * Dispatches `IdentityTask::RefreshIdentity`. Result via event.
 */
async identityRefresh(input: RefreshIdentityInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_refresh", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh all loaded identities' DPNS names.
 *
 * Dispatches `IdentityTask::RefreshLoadedIdentitiesOwnedDPNSNames`. Result via event.
 */
async identityRefreshDpnsNames() : Promise<DispatchTaskResponse> {
    return await TAURI_INVOKE("identity_refresh_dpns_names");
},
/**
 * Withdraw credits from an identity to a Core address.
 *
 * Dispatches `IdentityTask::WithdrawFromIdentity`. Result via event.
 */
async identityWithdraw(input: WithdrawFromIdentityInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_withdraw", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Transfer credits from one identity to another.
 *
 * Dispatches `IdentityTask::Transfer`. Result via event.
 */
async identityTransfer(input: TransferCreditsInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_transfer", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a key to an identity.
 *
 * Dispatches `IdentityTask::AddKeyToIdentity`. Result via event.
 */
async identityAddKey(input: AddKeyToIdentityInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_add_key", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Disable one or more keys on an identity.
 *
 * Dispatches `IdentityTask::DisableKeys`. Result via event.
 */
async identityDisableKeys(input: DisableKeysInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_disable_keys", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replace a key on an identity (disable old + add new atomically).
 *
 * Dispatches `IdentityTask::ReplaceKey`. Result via event.
 */
async identityReplaceKey(input: ReplaceKeyInput) : Promise<Result<DispatchTaskResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_replace_key", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load all local qualified identities from the database.
 */
async identityListLocal() : Promise<Result<QualifiedIdentityDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_list_local") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load all local user identities (non-masternode/evonode).
 */
async identityListUser() : Promise<Result<QualifiedIdentityDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_list_user") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load all local voting identities.
 */
async identityListVoting() : Promise<Result<QualifiedIdentityDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_list_voting") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single identity by its ID.
 */
async identityGetById(identityId: string) : Promise<Result<QualifiedIdentityDto | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_get_by_id", { identityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the alias for an identity.
 */
async identitySetAlias(input: SetIdentityAliasInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_set_alias", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the alias for an identity.
 */
async identityGetAlias(identityId: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_get_alias", { identityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load the custom identity ordering.
 */
async identityLoadOrder() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_load_order") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save the custom identity ordering.
 */
async identitySaveOrder(input: SaveIdentityOrderInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_save_order", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a local identity from the database.
 */
async identityDelete(input: DeleteIdentityInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_delete", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get identity summaries suitable for dropdown selectors.
 */
async identityListSummaries() : Promise<Result<IdentitySummaryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_list_summaries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all local DPNS names across all loaded identities.
 */
async identityLocalDpnsNames() : Promise<Result<DpnsNameEntryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("identity_local_dpns_names") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
scheduledVoteExecutedEvent: ScheduledVoteExecutedEvent,
spvStatusEvent: SpvStatusEvent,
taskErrorEvent: TaskErrorEvent,
taskResultEvent: TaskResultEvent,
walletUpdatedEvent: WalletUpdatedEvent,
zmqChainLockedBlockEvent: ZmqChainLockedBlockEvent,
zmqConnectionStatusEvent: ZmqConnectionStatusEvent,
zmqIsLockedTransactionEvent: ZmqIsLockedTransactionEvent
}>({
scheduledVoteExecutedEvent: "scheduled-vote-executed-event",
spvStatusEvent: "spv-status-event",
taskErrorEvent: "task-error-event",
taskResultEvent: "task-result-event",
walletUpdatedEvent: "wallet-updated-event",
zmqChainLockedBlockEvent: "zmq-chain-locked-block-event",
zmqConnectionStatusEvent: "zmq-connection-status-event",
zmqIsLockedTransactionEvent: "zmq-is-locked-transaction-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Input for adding a key to an identity.
 */
export type AddKeyToIdentityInput = {
/**
 * Identity ID (hex).
 */
identityId: string;
/**
 * Key type (e.g., "ECDSA_SECP256K1", "BLS12_381").
 */
keyType: string;
/**
 * Key purpose (e.g., "AUTHENTICATION", "VOTING", "TRANSFER").
 */
purpose: string;
/**
 * Security level (e.g., "HIGH", "MEDIUM").
 */
securityLevel: string;
/**
 * Private key as hex string (32 bytes).
 */
privateKeyHex: string }
/**
 * Input for deleting a local identity.
 */
export type DeleteIdentityInput = {
/**
 * Identity ID (hex) to delete.
 */
identityId: string }
/**
 * Input for disabling keys on an identity.
 */
export type DisableKeysInput = {
/**
 * Identity ID (hex).
 */
identityId: string;
/**
 * Key IDs to disable.
 */
keyIds: number[] }
/**
 * Response from dispatching a backend task.
 */
export type DispatchTaskResponse = {
/**
 * Unique task ID. Listen for `TaskResultEvent` or `TaskErrorEvent` with
 * this ID to receive the result.
 */
taskId: string }
/**
 * A DPNS name entry with its owning identity.
 */
export type DpnsNameEntryDto = {
/**
 * Identity ID (hex) that owns this name.
 */
identityId: string;
/**
 * The DPNS name (e.g., "alice.dash").
 */
name: string;
/**
 * Timestamp when the name was acquired.
 */
acquiredAt: number }
/**
 * DPNS name info attached to an identity.
 */
export type DpnsNameInfoDto = {
/**
 * The registered DPNS name (e.g., "alice.dash").
 */
name: string;
/**
 * Timestamp when the name was acquired.
 */
acquiredAt: number }
/**
 * A sample DTO demonstrating tauri-specta type generation.
 */
export type GreetResponse = { message: string; timestamp_ms: number }
/**
 * A public key on an identity.
 */
export type IdentityKeyDto = {
/**
 * Key ID within the identity.
 */
keyId: number;
/**
 * Key type (ECDSA_SECP256K1, BLS12_381, ECDSA_HASH160, etc.).
 */
keyType: string;
/**
 * Key purpose (AUTHENTICATION, VOTING, TRANSFER, OWNER, etc.).
 */
purpose: string;
/**
 * Security level (MASTER, CRITICAL, HIGH, MEDIUM, etc.).
 */
securityLevel: string;
/**
 * Public key data as hex string.
 */
data: string;
/**
 * Whether this key is disabled.
 */
isDisabled: boolean;
/**
 * Disabled at timestamp (if disabled).
 */
disabledAt: number | null;
/**
 * Whether we have the corresponding private key in local storage.
 */
hasPrivateKey: boolean }
/**
 * Status of an identity on the platform.
 */
export type IdentityStatusDto = "unknown" | "pendingCreation" | "active" | "notFound" | "failedCreation"
/**
 * Minimal identity reference for dropdowns and selectors.
 */
export type IdentitySummaryDto = {
/**
 * Platform identifier as hex string.
 */
id: string;
/**
 * Display name: alias or truncated ID.
 */
displayName: string;
/**
 * Identity type.
 */
identityType: IdentityTypeDto;
/**
 * Current balance in credits.
 */
balance: number }
/**
 * Type of identity (User, Masternode, Evonode).
 */
export type IdentityTypeDto = "user" | "masternode" | "evonode"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Input for loading an existing identity by ID or from a wallet.
 */
export type LoadIdentityInput = {
/**
 * Identity ID as hex or base58 string.
 */
identityId: string;
/**
 * Type of identity (User, Masternode, Evonode).
 */
identityType: IdentityTypeDto;
/**
 * User alias to assign.
 */
alias: string;
/**
 * Voting private key (hex or WIF, empty string if none).
 */
votingPrivateKey: string;
/**
 * Owner private key (hex or WIF, empty string if none).
 */
ownerPrivateKey: string;
/**
 * Payout address private key (hex or WIF, empty string if none).
 */
payoutAddressPrivateKey: string;
/**
 * Additional private keys (hex or WIF).
 */
keys: string[];
/**
 * Whether to try deriving keys from loaded wallets.
 */
deriveKeysFromWallets: boolean;
/**
 * Optional wallet seed hash to associate with.
 */
selectedWalletSeedHash: string | null }
/**
 * Network identifier matching Dash SDK's Network enum.
 */
export type NetworkDto = "dash" | "testnet" | "devnet" | "regtest"
/**
 * Network availability info returned to the frontend.
 */
export type NetworkInfo = {
/**
 * Currently active network.
 */
activeNetwork: NetworkDto;
/**
 * All networks that have valid configurations.
 */
availableNetworks: NetworkDto[] }
/**
 * Serializable version of `QualifiedIdentity`.
 * This is the primary identity DTO sent to the frontend for display and selection.
 */
export type QualifiedIdentityDto = {
/**
 * Platform identifier as hex string.
 */
id: string;
/**
 * Identity type (User, Masternode, Evonode).
 */
identityType: IdentityTypeDto;
/**
 * User-assigned alias.
 */
alias: string | null;
/**
 * Current balance in credits.
 */
balance: number;
/**
 * Public keys on this identity.
 */
keys: IdentityKeyDto[];
/**
 * DPNS names registered for this identity.
 */
dpnsNames: DpnsNameInfoDto[];
/**
 * Seed hashes of associated wallets (hex-encoded).
 */
associatedWalletHashes: string[];
/**
 * The wallet index used during registration (if applicable).
 */
walletIndex: number | null;
/**
 * Top-up history: map of index → amount.
 */
topUps: TopUpEntryDto[];
/**
 * Current status on the platform.
 */
status: IdentityStatusDto;
/**
 * Network this identity belongs to.
 */
network: NetworkDto;
/**
 * Associated voter identity ID (if any, for masternodes/evonodes).
 */
voterIdentityId: string | null;
/**
 * Associated operator identity ID (if any).
 */
operatorIdentityId: string | null }
/**
 * Input for refreshing a single identity.
 */
export type RefreshIdentityInput = {
/**
 * Identity ID (hex) to refresh.
 */
identityId: string }
/**
 * Input for registering a DPNS name.
 */
export type RegisterDpnsNameCommandInput = {
/**
 * Identity ID (hex) that will own the name.
 */
identityId: string;
/**
 * The DPNS name to register (without .dash suffix).
 */
name: string }
/**
 * Input for replacing a key on an identity.
 */
export type ReplaceKeyInput = {
/**
 * Identity ID (hex).
 */
identityId: string;
/**
 * Key ID to replace (old key).
 */
oldKeyId: number;
/**
 * New key type.
 */
newKeyType: string;
/**
 * New key purpose.
 */
newPurpose: string;
/**
 * New security level.
 */
newSecurityLevel: string;
/**
 * New private key as hex string (32 bytes).
 */
newPrivateKeyHex: string }
/**
 * Input for saving custom identity ordering.
 */
export type SaveIdentityOrderInput = {
/**
 * Ordered list of identity IDs (hex).
 */
identityIds: string[] }
/**
 * Emitted when a scheduled vote is automatically cast.
 */
export type ScheduledVoteExecutedEvent = {
/**
 * The contested name the vote was for.
 */
contestedName: string;
/**
 * Voter identity ID (hex).
 */
voterId: string;
/**
 * Whether the vote was cast successfully.
 */
success: boolean;
/**
 * Error message if the vote failed.
 */
error: string | null }
/**
 * Input for batch search of identities from a wallet.
 */
export type SearchIdentitiesUpToIndexInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string;
/**
 * Maximum identity index to search up to.
 */
maxIdentityIndex: number }
/**
 * Input for searching identity by DPNS name.
 */
export type SearchIdentityByDpnsNameInput = {
/**
 * DPNS name without .dash suffix.
 */
name: string;
/**
 * Optional wallet seed hash for key derivation.
 */
walletSeedHash: string | null }
/**
 * Input for searching identities from a wallet.
 */
export type SearchIdentityFromWalletInput = {
/**
 * Wallet seed hash (hex).
 */
walletSeedHash: string;
/**
 * Identity index to search at.
 */
identityIndex: number }
/**
 * Input for setting identity alias.
 */
export type SetIdentityAliasInput = {
/**
 * Identity ID (hex).
 */
identityId: string;
/**
 * New alias (None to clear).
 */
alias: string | null }
/**
 * High-level SPV status values.
 */
export type SpvStatusDto = "idle" | "starting" | "syncing" | "running" | "stopping" | "stopped" | "error"
/**
 * Emitted when SPV sync status changes.
 */
export type SpvStatusEvent = {
/**
 * The network this SPV instance belongs to.
 */
network: NetworkDto;
/**
 * Current SPV status.
 */
status: SpvStatusDto;
/**
 * Sync progress as a percentage (0.0–100.0), if syncing.
 */
syncProgressPct: number | null;
/**
 * Current header height, if known.
 */
headerHeight: number | null;
/**
 * Number of connected peers.
 */
connectedPeers: number;
/**
 * Error message, if status is Error.
 */
error: string | null }
/**
 * Emitted when a backend task fails.
 */
export type TaskErrorEvent = {
/**
 * Unique task ID assigned at dispatch time.
 */
taskId: string;
/**
 * User-friendly error message suitable for display.
 */
message: string;
/**
 * Technical error details for debugging.
 */
details: string;
/**
 * Whether the operation can be retried.
 */
recoverable: boolean }
/**
 * Emitted when a backend task completes successfully.
 *
 * The `result_type` field is a discriminant string (e.g. "Identity", "Wallet",
 * "Contract") that the frontend can match on. The `payload` is the serialized
 * result data as JSON value. This design avoids needing to represent the entire
 * `BackendTaskSuccessResult` enum in the TypeScript type system up front —
 * individual domain result types will be defined as the IPC commands are
 * implemented in phases 1.4–1.7.
 */
export type TaskResultEvent = {
/**
 * Unique task ID assigned at dispatch time.
 */
taskId: string;
/**
 * The domain of the result (e.g. "Identity", "Wallet", "None", "Refresh").
 */
resultType: string;
/**
 * The serialized result payload. `null` for `None` and `Refresh` results.
 */
payload: JsonValue | null }
/**
 * A top-up history entry.
 */
export type TopUpEntryDto = { index: number; amount: number }
/**
 * Input for transferring credits to another identity.
 */
export type TransferCreditsInput = {
/**
 * Source identity ID (hex).
 */
fromIdentityId: string;
/**
 * Destination identity ID (hex).
 */
toIdentityId: string;
/**
 * Amount to transfer in credits.
 */
credits: number;
/**
 * Optional key ID to use for signing.
 */
keyId: number | null }
/**
 * Emitted when a wallet's balance or state changes.
 */
export type WalletUpdatedEvent = {
/**
 * Which wallet changed (seed hash, hex-encoded).
 */
walletSeedHash: string;
/**
 * The network this wallet belongs to.
 */
network: NetworkDto }
/**
 * Input for withdrawing credits from an identity.
 */
export type WithdrawFromIdentityInput = {
/**
 * Identity ID (hex) to withdraw from.
 */
identityId: string;
/**
 * Optional destination Core address.
 */
toAddress: string | null;
/**
 * Amount to withdraw in credits.
 */
credits: number;
/**
 * Optional key ID to use for signing.
 */
keyId: number | null }
/**
 * Emitted when a chain-locked block is received via ZMQ.
 */
export type ZmqChainLockedBlockEvent = {
/**
 * The network this event belongs to.
 */
network: NetworkDto;
/**
 * Block height.
 */
blockHeight: number;
/**
 * Block hash (hex).
 */
blockHash: string;
/**
 * Number of transactions in the block.
 */
txCount: number }
/**
 * Emitted when ZMQ connection status changes.
 */
export type ZmqConnectionStatusEvent = {
/**
 * The network this status change belongs to.
 */
network: NetworkDto;
/**
 * Whether ZMQ is currently connected.
 */
connected: boolean }
/**
 * Emitted when an InstantSend-locked transaction is received via ZMQ.
 */
export type ZmqIsLockedTransactionEvent = {
/**
 * The network this event belongs to.
 */
network: NetworkDto;
/**
 * Transaction ID (hex).
 */
txid: string;
/**
 * Serialized transaction data (hex).
 */
rawTx: string;
/**
 * Number of UTXOs affected by this transaction.
 */
affectedUtxoCount: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
