// Prevents additional console window on Windows in release
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use serde::{Deserialize, Serialize};
use specta::Type;
use specta_typescript::Typescript;
use tauri_specta::{collect_commands, collect_events, Builder, Event};

/// A sample DTO demonstrating tauri-specta type generation.
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct GreetResponse {
    pub message: String,
    pub timestamp_ms: u64,
}

/// A sample event demonstrating tauri-specta event type generation.
#[derive(Debug, Clone, Serialize, Deserialize, Type, Event)]
pub struct BackendNotification {
    pub title: String,
    pub body: String,
}

#[tauri::command]
#[specta::specta]
fn greet(name: String) -> GreetResponse {
    GreetResponse {
        message: format!("Hello, {}! Welcome to Dash Evo Tool.", name),
        timestamp_ms: std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64,
    }
}

#[tauri::command]
#[specta::specta]
async fn get_app_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

fn main() {
    let builder = Builder::<tauri::Wry>::new()
        .commands(collect_commands![greet, get_app_version])
        .events(collect_events![BackendNotification]);

    #[cfg(debug_assertions)]
    builder
        .export(
            Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("/* eslint-disable */\n// This file is auto-generated by tauri-specta. Do not edit."),
            "../src/frontend/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    tauri::Builder::default()
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running Dash Evo Tool");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn greet_returns_expected_response() {
        let response = greet("Alice".into());
        assert_eq!(response.message, "Hello, Alice! Welcome to Dash Evo Tool.");
        assert!(response.timestamp_ms > 0);
    }

    #[test]
    fn greet_handles_empty_name() {
        let response = greet(String::new());
        assert_eq!(response.message, "Hello, ! Welcome to Dash Evo Tool.");
    }

    #[test]
    fn greet_response_serializes() {
        let response = GreetResponse {
            message: "test".into(),
            timestamp_ms: 12345,
        };
        let json = serde_json::to_string(&response).unwrap();
        assert!(json.contains("\"message\":\"test\""));
        assert!(json.contains("\"timestamp_ms\":12345"));
    }

    #[test]
    fn greet_response_deserializes() {
        let json = r#"{"message":"test","timestamp_ms":12345}"#;
        let response: GreetResponse = serde_json::from_str(json).unwrap();
        assert_eq!(response.message, "test");
        assert_eq!(response.timestamp_ms, 12345);
    }

    #[test]
    fn backend_notification_serializes() {
        let event = BackendNotification {
            title: "Test".into(),
            body: "Body".into(),
        };
        let json = serde_json::to_string(&event).unwrap();
        assert!(json.contains("\"title\":\"Test\""));
        assert!(json.contains("\"body\":\"Body\""));
    }
}
