name: Release Dash Evo Tool

on:
  push:
    tags:
      - "v*"
      - "v*-dev.*"
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag:
        description: "Version (i.e. v0.1.0)"
        required: false

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  build-and-release:
    name: Build and Release Dash Evo Tool
    strategy:
      matrix:
        include:
          - name: "linux-x86_64"
            runs-on: "ubuntu"
            target: "x86_64-unknown-linux-gnu"
            platform: "linux-x86_64"
          - name: "linux-arm64"
            runs-on: "ubuntu-arm"
            target: "aarch64-unknown-linux-gnu"
            platform: "linux-arm64"

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Setup prerequisites
        run: |
          mkdir -p dash-evo-tool/

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install essentials
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config clang cmake unzip libsqlite3-dev gcc-aarch64-linux-gnu zip && uname -a && cargo clean

      - name: Install protoc (ARM)
        if: ${{ matrix.platform == 'linux-arm64' }}
        run: curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v25.2/protoc-25.2-linux-aarch_64.zip && sudo unzip -o protoc-25.2-linux-aarch_64.zip -d /usr/local bin/protoc && sudo unzip -o protoc-25.2-linux-aarch_64.zip -d /usr/local 'include/*' && rm -f protoc-25.2-linux-aarch_64.zip
        env:
          PROTOC: /usr/local/bin/protoc

      - name: Install protoc (AMD)
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
        run: curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v25.2/protoc-25.2-linux-x86_64.zip && sudo unzip -o protoc-25.2-linux-x86_64.zip -d /usr/local bin/protoc && sudo unzip -o protoc-25.2-linux-x86_64.zip -d /usr/local 'include/*' && rm -f protoc-25.2-linux-x86_64.zip
        env:
          PROTOC: /usr/local/bin/protoc

      - name: Build project
        run: |
          cargo build --release --target ${{ matrix.target }}
          mv target/${{ matrix.target }}/release/dash-evo-tool dash-evo-tool/dash-evo-tool

      - name: Package release
        run: |
          zip -r dash-evo-tool-${{ matrix.platform }}.zip dash-evo-tool/

      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "dash-evo-tool-${{ matrix.platform }}.zip"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dash-evo-tool-${{ matrix.platform }}.zip
          path: dash-evo-tool-${{ matrix.platform }}.zip
          retention-days: 14

  attach-to-release:
    name: Attach Artifacts to Release
    if: github.event_name == 'release'
    needs: [build-and-release]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux AMD64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: dash-evo-tool-linux-x86_64.zip
      - name: Download Linux Arm64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: dash-evo-tool-linux-arm64.zip

      - name: Attach to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./dash-evo-tool-linux-x86_64.zip
            ./dash-evo-tool-linux-arm64.zip
